language: node_js
node_js:
  - '8'
dist: trusty
cache:
  directories:
    - node_modules
sudo: required
addons:
  apt:
    sources:
      - git-core
      - ubuntu-toolchain-r-test
    packages:
      - git
      - g++-4.9
env:
  - CXX=g++-4.9
before_install:
  - sudo apt-get update
  - npm explore npm -g -- npm install node-gyp@latest
install: npm install
jobs:
  include:
    - stage: test
      script: bash ./ci/test.sh
    - stage: deploy
      script: bash ./ci/deploy.sh
stages:
  - test
  - name: deploy
    if: branch = master
script: skip
